
# ============================================
# ABSTRACT
# ============================================
add_title(doc, "ABSTRACT")
add_para(doc, "")

add_para(doc, "Introduction: Stroke is the leading cause of death and permanent disability in Brazil, "
              "with approximately 100,000 new cases annually (MINISTÉRIO DA SAÚDE, 2023; GBD 2019 STROKE "
              "COLLABORATORS, 2021). Among survivors, about 70% present upper limb hemiparesis, severely "
              "compromising functional autonomy and quality of life (LANG et al., 2020; LAWRENCE et al., 2001). "
              "Conventional rehabilitation, while effective, faces limitations in access, cost, and therapeutic intensity "
              "(LO et al., 2010; MEHRHOLZ et al., 2018). Emerging technologies — brain-computer interfaces (BCI), "
              "immersive virtual reality (VR), and robotics — offer prospects for more intensive, personalized, and "
              "accessible intervention (LECUYER et al., 2008; VOURVOPOULOS et al., 2013). However, interoperability "
              "between neural signal acquisition systems and VR engines constitutes an architectural bottleneck that "
              "limits the clinical scalability of these solutions (LOTTE et al., 2012; HAL, 2023).")

add_para(doc, "Objective: To develop and validate a software translation and temporal synchronization layer that "
              "receives JSON messages generated by a CNN/LM EEG classifier, converts their probabilistic fields into "
              "continuous kinematic parameters of hand articulation, and transmits them to the Unity engine for "
              "synchronized rendering in the VR headset, enabling precise and low-latency hand movement projection "
              "in immersive neuromotor rehabilitation environments post-stroke.")

add_para(doc, "Methods: Applied technological research with experimental approach. The software layer will be "
              "implemented in Python, architected to receive JSON messages via real-time communication protocol "
              "(ZeroMQ/WebSocket), process neural classification fields (label, p_combined, ema, p_move, threshold), "
              "convert probabilities into kinematic parameters of 25 virtual hand joints, and transmit them to the Unity "
              "engine with circular buffer, interpolation, and latency compensation mechanisms. Validation will include "
              "end-to-end latency evaluation, jitter, temporal synchronization between JSON reception and rendered "
              "movement, and usability assessment, with feasibility analysis for deployment in public (SUS) and private "
              "health scenarios.")

add_para(doc, "Expected Results: Functional software layer with API and communication protocol documentation, "
              "Unity engine demonstrator with VR headset, latency below 150 ms with controlled jitter, comparative "
              "cost-effectiveness analysis, and scientific article submitted to A1-A2 Qualis journal in Health or Applied "
              "Computing.")

add_para(doc, "")
add_para(doc, "Keywords: Stroke; neuromotor rehabilitation; brain-computer interfaces; electroencephalography; "
              "convolutional neural networks; virtual reality; middleware; temporal synchronization; hemiparesis; "
              "health information technology.", indent=Cm(0))

page_break(doc)
print("Abstract finalizado.")